#!/usr/bin/env python
# -*- coding: latin1 -*-

import wx

class IMCFrame(wx.Frame):
    def __init__(self, *args, **kw):
        wx.Frame.__init__(self, None, wx.ID_ANY, 'Calculadora IMC')

        self.panel = wx.Panel(self)

        nomeLabel = wx.StaticText(self.panel, label = "Nome do Paciente:")
        self.nomeInput = wx.TextCtrl(self.panel, value = '')

        endLabel = wx.StaticText(self.panel, label="Endereço Completo:")
        self.endInput = wx.TextCtrl(self.panel, value ='')

        alturaLabel = wx.StaticText(self.panel, label="Altura (m)")
        self.alturaInput = wx.TextCtrl(self.panel, value ='')

        pesoLabel = wx.StaticText(self.panel, label="Peso (kg)")
        self.pesoInput = wx.TextCtrl(self.panel, value ='')

        self.resultado = wx.TextCtrl(self.panel, value = '', style = wx.TE_MULTILINE)

        botaoCalcular = wx.Button(self.panel, label = 'Calcular')
        botaoReiniciar = wx.Button(self.panel, label = 'Reiniciar')
        botaoSair = wx.Button(self.panel, label = 'Sair')

        self.Bind(wx.EVT_BUTTON, self.onCalcular, botaoCalcular)
        self.Bind(wx.EVT_BUTTON, self.onReiniciar, botaoReiniciar)
        self.Bind(wx.EVT_BUTTON, self.onSair, botaoSair)

        formSizer = wx.GridBagSizer(hgap = 5, vgap = 5)
        topSizer = wx.BoxSizer(wx.VERTICAL)

        formSizer.Add(nomeLabel, pos = (0,0), flag = wx.ALL|wx.ALIGN_CENTER_VERTICAL)
        formSizer.Add(self.nomeInput, pos = (0,1), flag = wx.ALL|wx.EXPAND, span=(1,3), border=2)

        formSizer.Add(endLabel, pos=(1, 0), flag=wx.ALL | wx.ALIGN_CENTER_VERTICAL, border=2)
        formSizer.Add(self.endInput, pos=(1, 1), flag=wx.ALL | wx.EXPAND, span=(1, 3), border=2)

        formSizer.Add(alturaLabel, pos = (2,0), flag = wx.ALL|wx.ALIGN_CENTER_VERTICAL, border = 2)
        formSizer.Add(self.alturaInput, pos=(2, 1), flag=wx.ALL | wx.EXPAND, border=2)

        formSizer.Add(self.resultado, pos=(2, 2),flag=wx.ALL | wx.EXPAND, border=2, span=(4, 2))
        formSizer.AddGrowableCol(2, 0)

        formSizer.Add(pesoLabel, pos=(3, 0), flag=wx.ALL | wx.ALIGN_CENTER_VERTICAL, border=2)
        formSizer.Add(self.pesoInput, pos=(3, 1), flag=wx.ALL | wx.EXPAND, border=2)


        formSizer.Add(botaoCalcular, pos=(6, 1), flag=wx.ALL, border=2)
        formSizer.Add(botaoReiniciar, pos=(6,2), flag = wx.ALL, border = 2)
        formSizer.Add(botaoSair, pos=(6,3), flag=wx.ALL, border = 2)

        topSizer.Add(formSizer, 0, wx.ALL | wx.EXPAND, 5)

        self.SetSizeHints(250, 230, 600, 230)

        self.panel.SetSizer(topSizer)
        topSizer.Fit(self)

    def onCalcular(self, event):
        altura = float(self.alturaInput.GetValue())
        peso = int(self.pesoInput.GetValue())
        self.resultado.SetValue("IMC: \n {}".format(str(peso/(altura*altura))))

    def onReiniciar(self, event):
        self.pesoInput.SetValue('')
        self.alturaInput.SetValue('')
        self.nomeInput.SetValue('')
        self.endInput.SetValue('')
        self.resultado.SetValue('')

    def onSair(self, event):
        self.Close()



app = wx.App()
frame = IMCFrame().Show()
app.MainLoop()
